config/routes.rb
Zatfish::Application.routes.draw do
  get "home/dashboard"
  match "/home/create_user_profile"=> "home#create_user_profile",:as=>'user_profile'
  match "/home/new_user_profile"=> "home#new_user_profile"
  match '/auth/:provider/callback'  => 'authorization#create'
  match '/auth/failure'             => 'authorization#failure'
  match 'home/csv' => 'home#csv', :via => :post
  match 'home/csvupload' => 'home#csvupload', :via => :get
  match 'home/categorylist/:id' => 'home#categorylist'
  match '/chart/:id' => 'home#chart'
  match 'admin_page'  => 'home#admin_page'
  match 'home/dashboard' => 'home#dashboard'
  match 'new_user'  => 'home#new_user'
  match 'create_user'  => 'home#create_user'
  match 'index'  => 'home#index'
  match 'login'  => 'api#login'
  match 'category'  => 'api#category'
  match 'new'  => 'api#new'
  match 'favourite'  => 'api#favourite'
  match 'favourite_list'  => 'api#favourite_list'
  match '/delet/:id' => 'home#delet'
  match 'favourite_delete'  => 'api#favourite_delete'
 

  devise_for :users, :controllers => {:registrations => "devise/registrations"}

  
   root :to => 'home#index'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_filter :authenticate_user!
  
  require 'csv'
 
  def index
  if current_user.position  == 'admin'
  redirect_to admin_page_path
  else
  redirect_to home_dashboard_path
  end
  end
  def dashboard
  @cate =[]
  p "-----------#{current_user.position}-----"
  case current_user.position
   when 'admin'
   User::ADMIN_CATEG.map{|categ| (@cate << categ) }
   when 'ceo'
   User::CEO_CATEG.map{|categ| (@cate << categ) }
   when 'manager'
   User::MANAGER_CATEG.map{|categ| (@cate << categ) }
   else
   User::STAFF_CATEG.map{|categ| (@cate << categ) }
   
  end
  
  end
  def new_user
  @current_user= current_user.email
   @user = User.new  
  end
  def create_user
  @current_user= current_user.email
  p "--------#{params.inspect}-------"
  @user = User.new(params[:user])
  @user.position = params[:position]
  @user.confirmed_at = Time.now
  p "----dd----#{@user.inspect}-------"
   if !@user.save
      p "----@user.errors"
      render :action=> new_user_path
   else
      p "---s-----#{@create_user}"
	  flash[:notice] = 'User added and email send to the created user'
	  redirect_to admin_page_path
   end  
	 
  
  end
  def admin_page
    @current_user= current_user.email
  end
  def new_user_profile
    @user_profile = UserProfile.new
  end
  
  def create_user_profile
    #@user_profile = UserProfile.new(params[:user_profile])
   # if @user_profile.valid?
     # @user_profile.user_id = current_user.id
     # @user_profile.save
     # flash[:notice] = 'UserProfile was created successfully.'
      #redirect_to home_dashboard_path
    #else
      #render :action=>'new_user_profile'
   # end
  end
  
  def csvupload
  
      @csvupload = Csvupload.new
	  
	  p"================#{@opt.inspect}============="
  end
  
  def csv
  
    p"-------------#{params.inspect}---------"
	
    @csvupload= Csvupload.new( params[:csvupload] )
	p"================#{@csvupload.inspect}============="
    if @csvupload.save
	flash[:notice] = 'CSV file uploaded successfully.'
	redirect_to admin_page_path
	else
	flash[:error] = 'CSV file uploaded successfully.'
	redirect_to 'home/csvupload'
    end
  end
 
  def categorylist
  	 @category = params[:id]
	 @csvreports = Csvupload.where("category = ?", params[:id])
	 
  end
  def chart
    @csvreports = Csvupload.where("id = ?", params[:id]).first

  case @csvreports.category
  when 'Weekly'
  @yaxis_unit = 'Percentage'
  @yaxis_sub = ''
  when "Sales"
  @yaxis_unit = 'No of Sales'
  @yaxis_sub = ''
  when "Employee"
  @yaxis_unit = 'Strength'
  @yaxis_sub = ''
  when "Projects"
  @yaxis_unit = 'No of Projects'
  @yaxis_sub = ''
  when "Profit&Loss"
  @yaxis_unit = 'Percentage'
  @yaxis_sub = ''
  when "Expenses"
  @yaxis_unit = 'Amount'
  @yaxis_sub  = ''
  when "Bussiness Prospect"
  @yaxis_unit = 'No of Bussiness'
  @yaxis_sub = ''
  when "Technology Prospect"
  @yaxis_unit = 'No of Technology'
  @yaxis_sub = ''
  else
  @yaxis_unit = 'No of Resources'
  @yaxis_sub = ''
  end
  @chart_name = (@csvreports.csvfile_file_name).split('.cs')
  p "---ch------#{@chart_name}----------"
  #url = "https://dl.dropbox.com/0/view/j1g15ltz8e0lzz3/Apps/sybrantlive/original/4/sheet_test.csv"
  url = @csvreports.csvfile.url 
  data = open("#{url}")
  @tabled= CSV.parse(data)
  a1 = @tabled[0]
  @tab_transpose = @tabled.transpose
  @c={}
  b1=[]
  k = @tabled[0].length - 1
  i = 1
   for i in 0..k
     @tab_transpose[i].shift
     b1 <<  @tab_transpose[i]
   end
   a1.shift
   b1.shift
   a1.each_with_index {|k,i|@c[k] = b1[i]}
   render :template => '/home/chart'
  end
  
  def delet
    @csvreports = Csvupload.where("id = ?", params[:id]).first
	favour = Favourate.where(:file_fav => (@csvreports.id).to_s)
	favour.destroy_all if (favour != [])
	@csvreports.delete
	flash[:notice] = 'CSV file deleted successfully.'
	redirect_to home_dashboard_path
  end
  
end

app/views/home/admin_page.html.erb
<div class="logo"><a href="#">
<img src="/assets/logo.png" width="340" height="135"  align="middle"/></a></div>

<h4>Welcome <%=@current_user.capitalize%>!</h4>
<center>
<%= link_to "Sign out", destroy_user_session_path %></center>
<div class="Sign-In" style="width:1200px">
<h2> Reports </h2>
<ul>
<li><%= link_to "Upload New CSV", home_csvupload_path %></li>
<li><%= link_to "Create User", new_user_path %></li>
<li><%= link_to "Chart Category", home_dashboard_path %></li>



</div>

app/views/home/categorylist.html.erb
<div class="logo"><a href="#">
<img src="/assets/logo.png" width="340" height="135"  align="middle"/></a></div>

<h4>Welcome <%=current_user.email.capitalize%>!</h4>

<center>
<%= link_to "Sign out", destroy_user_session_path %></center>
<div class="Sign-In" style="width:1200px">
<div><%= link_to 'back to dashboard', "/home/dashboard"%></div>
<h2> <%= @category%> Reports   </h2>

<% if @csvreports != []%>
   <table>
   <%@csvreports.each do |csv|%>
   <tr><td style="width:400px;">
      <%name =  (csv.csvfile_file_name).split('.cs')%>
	  <%name_id = csv.id%>
	  <%= link_to name[0], "/chart/#{name_id}"%></td>
	    <% if(current_user.email == 'admin') %>
		<td> <%= link_to 'Delete', "/delet/#{name_id}"%></td>
		<% end %>
   </tr>
   
   <% end %>
   </table>
<% else %>
   <div><center>Currently no files uploaded</center></div>   
<% end %>

</div>

app/views/home/chart.html.erb
<div class="logo"><a href="#">
<img src="/assets/logo.png" width="340" height="135"  align="middle"/></a></div>
<h4>Welcome <%=current_user.email.capitalize%>!</h4>
<center>
<%= link_to "Sign out", destroy_user_session_path %></center>
<div class="Sign-In" style="width:1200px">
<div><%= link_to 'back to dashboard', "/home/dashboard"%></div>
<h2> <%=@csvreports.category%> Report   </h2>
<div id="container"></div>
</div>


<script>
var chart1;
$(document).ready(function() {

    var dyn_height = (<%=raw @tab_transpose[0] %>.length) * 110;
    $('#container').css('height',dyn_height);

     chart1 = ({
         chart: {
            renderTo: 'container',
            type: 'bar'
         },
         title: {
            text: '<%= @chart_name[0]%>'
         },
         xAxis: {
            categories: <%=raw @tab_transpose[0] %>
         },
         yAxis: {
            title: {
               text: '<%= @yaxis_unit %>'
            },
         labels: {
                   formatter: function() {
                       return this.value +'<%= @yaxis_sub%>';
                 }
				}
		 
        },
		 series: []
         
      });
	  <% @c.each do|key, value| %>
	   var c = <%= value.map{|i|  i.to_i} %>
	      
    	chart1.series.push({
		
		name: '<%= key %>',
		data: c
		})
		 <% end %>
	  var chart = new Highcharts.Chart(chart1);
   });
   </script>

app/views/home/create_user_profile.html.erb
<table>
<%= form_for '/home/create_user_profile' do |f| %>
<tr>
<%= @user_profile.errors.full_messages.first if @user_profile.errors.any? %>
</tr>
<tr>
  <td><%= f.label :profile_name %>:</td>
  <td><%= f.text_field :profile_name %></td>
  
</tr>
<tr>
  <td><%= f.label :user_id %>:</td>
  <td><%= text_field_tag :user_id, current_user.id %></td>
</tr>
<tr>
  <td>Connect Facebook</td>
</tr>
<tr>
  <td>Connect Twitter</td>
</tr>
<tr>
  <td>Connect Youtube</td>
</tr>
<tr>
  <td><%= f.submit %></td>
</tr>


<% end %>
  </table>

app/views/home/csvupload.html.erb
<div class="logo"><a href="#">
<img src="/assets/logo.png" width="340" height="135"  align="middle"/></a></div>

<h4>Welcome <%=current_user.email.capitalize%>!</h4>
<center>
<%= link_to "Sign out", destroy_user_session_path %></center>
<div class="Sign-In">
<div><%= link_to 'Back to Main_Page', admin_page_path%></div>
</br>
<h4>Upload CSV for Category</h4>
<%= form_for @csvupload, :url => home_csv_path, :html => { :multipart => true } do |form| %>
  <%= form.select :category, options_for_select([["Select", ""], "Weekly", "Sales", "Employee", "Projects", "Profit&Loss","Expenses","Bussiness_Propect","Technology_Propect","Resource_Demand"]), :class => 'genForm_dropBox' %>
  <br/>
  <br/>
  <%= form.file_field :csvfile %> <br/>
  <br/>
  <%= form.submit%>
<% end %>
</div>

app/views/home/dashboard.html.erb
<div class="logo"><a href="#">
<img src="/assets/logo.png" width="340" height="135"  align="middle"/></a></div>

<h4>Welcome <%=current_user.email.capitalize%>!</h4>
<center>
<%= link_to "Sign out", destroy_user_session_path %></center>
<div class="Sign-In" style="width:1200px">
<% if (current_user.email) == 'admin' %>
<div><%= link_to 'Back to Main_Page', admin_page_path%></div>
<% end %>
<h2> Reports </h2>
<% @cate.each do|categ| %>
<%img = categ.to_s%>
<img src="/assets/<%=img%>.png" width="53" height="44"  align="middle"/> <%= link_to categ, :action=>"categorylist" ,:id=> categ %> <br><br>
<% end %>
</div>

app/views/home/new_user.html.erb
<div class="logo"><a href="#">
<img src="/assets/logo.png" width="340" height="135"  align="middle"/></a></div>

<h4>Welcome <%=@current_user.capitalize%>!</h4>
<center>
<%= link_to "Sign out", destroy_user_session_path %></center>
<div class="Sign-In" style="width:1200px">
<div><%= link_to 'Back to Main_Page', admin_page_path%></div>
<h2> Create User  </h2>

<%= form_for(@user,:url => create_user_path) do |f| %>
 <p class="float-LT">
<table>
 <tr>
 <td><%= f.label :User_Name %></td>
 <td><%= f.text_field :email,  :class=>"error"%></td><td><p><span class="err-msg"><%=@user.errors[:email][0]%></span></p></td></tr>
 <tr><td></td><td><p><span class="hint">eg:g@go.com</span></p></td></tr>
   
   
   
  

</p>

<p class="float-LT">

  
  <tr><td><%= f.label :password %></td>
  <td><%= f.password_field :password ,:class=>"error"%></td><td><p><span class="err-msg"><%=@user.errors[:password][0]%></span></p></td></tr>
  <tr><td></td><td><p><span class="hint">Minimum 6 characters</span></p></td></tr>
   
  
</p>


<p class="float-LT">
<tr><td>Position:</td>

<td ><span style='margin-left:1px;'>CEO<%= radio_button_tag(:position, "ceo") %>Manager<%= radio_button_tag(:position, "manager") %>Staff<%= radio_button_tag(:position, "staff") %></span></td><td><p><span class="err-msg"><%=@user.errors[:position][0]%><span></p></td></tr>
</p>
<tr><td></br></td></tr>
<tr><td><%= f.submit "create" %></td></tr>

<% end %>
</table>
</div>

app/views/home/new_user_profile.html.erb
<table>
<%= form_for @user_profile do |f| %>
<%= @user_profile.errors.full_messages.first if @user_profile.errors.any? %><br/>
<tr>
  <td><%= f.label :profile_name %>:</td>
  <td><%= f.text_field :profile_name %></td>
</tr>

<tr>
  <td><%= f.label :user_id %>:</td>
  <td><%= text_field_tag :user_id, current_user.id %></td>
</tr>

<tr>
  <th><link_to 'Connect facebook','/auth/facebook'></th>
  <th>Connect Twitter</th>
  <th>Connect Youtube</th>
</tr>

<tr>
  <td><%= f.submit %></td>
</tr>

<% end %>
  </table>